language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install nose

script:
  - python setup.py nosetests --verbosity=2 --with-doctest --doctest-extension=rst

notifications:
  email: false
